### ISSUE TITLE
Will not install in VS 2017 V15.7.3 

### ISSUE THREAD

**Issue by rpeaugh** [Dealogic/cloc-vsts-extension#2]
From the log:
6/3/2018 8:57:44 PM - Microsoft VSIX Installer
6/3/2018 8:57:44 PM - -------------------------------------------
6/3/2018 8:57:44 PM - vsixinstaller.exe version:
6/3/2018 8:57:44 PM - 15.7.105+ga2c5d563c6
6/3/2018 8:57:44 PM - -------------------------------------------
6/3/2018 8:57:44 PM - Command line parameters:
6/3/2018 8:57:44 PM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\rpeaugh\Downloads\Chrome\Dealogic.cloc-vsts-extension-1.0.0 (2).vsix
6/3/2018 8:57:44 PM - -------------------------------------------
6/3/2018 8:57:44 PM - Microsoft VSIX Installer
6/3/2018 8:57:44 PM - -------------------------------------------
6/3/2018 8:57:44 PM - Initializing Install...
6/3/2018 8:57:44 PM - Extension Details...
6/3/2018 8:57:44 PM - 	Identifier         : cloc-vsts-extension
6/3/2018 8:57:44 PM - 	Name               : Count Lines of Code
6/3/2018 8:57:44 PM - 	Author             : Dealogic
6/3/2018 8:57:44 PM - 	Version            : 1.0.0
6/3/2018 8:57:44 PM - 	Description        : Count Lines of Code with cloc CLI by Al Danial.
6/3/2018 8:57:44 PM - 	Locale             : en-US
6/3/2018 8:57:44 PM - 	MoreInfoURL        : 
6/3/2018 8:57:44 PM - 	InstalledByMSI     : False
6/3/2018 8:57:44 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/3/2018 8:57:44 PM - 
6/3/2018 8:57:44 PM - 	SignatureState     : Unsigned
6/3/2018 8:57:44 PM - 	Supported Products : 
6/3/2018 8:57:44 PM - 		Microsoft.VisualStudio.Services
6/3/2018 8:57:44 PM - 			Version : 
6/3/2018 8:57:44 PM - 
6/3/2018 8:57:44 PM - 	References         : 
6/3/2018 8:57:44 PM - Signature Details...
6/3/2018 8:57:44 PM - 	Extension is not signed.
6/3/2018 8:57:44 PM - 
6/3/2018 8:57:44 PM - Searching for applicable products...
6/3/2018 8:57:44 PM - Found installed product - Global Location
6/3/2018 8:57:44 PM - Found installed product - Visual Studio Professional 2017
6/3/2018 8:57:44 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by jkanczler** [comment]
It seems you're trying to install this for Visual Studio Professional 2017. But it's a Team Services extension, so if you have an on-premise TFS Server, you can install this onto that product as an extension.

```
6/3/2018 8:57:44 PM - Searching for applicable products...
6/3/2018 8:57:44 PM - Found installed product - Global Location
6/3/2018 8:57:44 PM - Found installed product - Visual Studio Professional 2017
6/3/2018 8:57:44 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```
