### ISSUE TITLE
Git Link Changed

### ISSUE THREAD

**Issue by Skinner007** [Dealogic/cloc-vsts-extension#4]
The cloc git download link was updated from  .../download/vX.X/... to .../download/X.X/... Please correct the download script to account for this change as it causes the build step to fail. Manually changing the script in each task cache temporarily resolves the issue, but it would be great if that change could be applied to the task in the marketplace.

**Comment by Swiftwork** [comment]
Original:
```
https://github.com/AlDanial/cloc/releases/download/v1.72/cloc-1.72.exe
````
Migrated to:
```
https://github.com/AlDanial/cloc/releases/download/1.72/cloc-1.72.exe
````
Latest: 
```
https://github.com/AlDanial/cloc/releases/download/1.80/cloc-1.80.exe
```
